
services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        container_name: postgres-elfsight
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-elfsight-test}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nXJrsY6S}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
        ports:
            - 5433:5432
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-elfsight-test}", "-U", "${POSTGRES_USER:-postgres}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        networks:
            my-net:
                ipv4_address: 172.18.0.3
    redis:
        image: redis:7.4.3
        container_name: redis-elfsight
        mem_limit: 200mb
        ports:
            - 6379:6379
            - 8001:8001
        networks:
            my-net:
                ipv4_address: 172.18.0.2
    nginx:
        image: nginx
        container_name: nginx-elfsight
        #   restart: always
        ports:
            - 84:80
        volumes:
            - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './:/var/www/elfsight'
        networks:
            - my-net
        depends_on:
            - symfony
    symfony:
        container_name: symfony
        volumes:
            - './:/var/www/elfsight'
        ports:
            - 9000:9000
        build:
            dockerfile: ./docker/elfsight.dock
        command: sh -c "composer install && composer update --optimize-autoloader && php bin/console doctrine:migrations:migrate --no-interaction -q && php bin/console episode:import && php-fpm"
        networks:
            - my-net
        depends_on:
            - database
            - redis
volumes:
    database_data:
networks:
    my-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/24
